In [1]:
#Packages And Librarys
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [2]:
#Taking Data
x=np.array([[1,2],[2,5],[3,9],[4,13],[5,17]])
y=np.array([3,1,5,9,6])

In [3]:
T=PolynomialFeatures(degree=2,include_bias=False)
T.fit(x)
x_=T.transform(x)
model=LinearRegression(fit_intercept=False).fit(x_,y)
print(x_)

[[  1.   2.   1.   2.   4.]
 [  2.   5.   4.  10.  25.]
 [  3.   9.   9.  27.  81.]
 [  4.  13.  16.  52. 169.]
 [  5.  17.  25.  85. 289.]]


In [4]:
y_pre=model.predict(x_)

In [5]:
print("Predict Score: ",model.score(x_,y_pre))
print("Normal Score : ",model.score(x_,y))

Predict Score:  1.0
Normal Score :  0.9334239130434787


In [6]:
print(y_pre)
print(y)

[3.   0.65 6.05 7.95 6.35]
[3 1 5 9 6]


In [7]:
print("b0: ",model.intercept_)
print("b1: ",model.coef_)
y_rc=model.intercept_+np.sum(model.coef_*x_,axis=1)
print("Rechecked Y predict Values : ",y_rc)

b0:  0.0
b1:  [ -6.75936073  10.12134703 -10.58196347  -2.10936073   1.0793379 ]
Rechecked Y predict Values :  [3.   0.65 6.05 7.95 6.35]
